### ISSUE TITLE
13.2 - npm install broken

### ISSUE THREAD

**Issue by ZuSe** [twilio/twilio-conversations.js#2]
When I try to install 13.2 via npm I get the following error:

```
    Error: ENOENT: no such file or directory, symlink '../lib' -> 'node_modules/lib'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:945:18)
    at Object.<anonymous> (../node_modules/twilio-conversations/scripts/postinstall.js:4:41)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3

```
I am running npm 3.3.15 on Ubuntu 14.04 LTS.
Also tried it with executing npm cache clean before.

**Comment by markandrus** [comment]
@ZuSe are you by any chance using Windows? I believe the way to fix this is to change [lines 4 and 5 of scripts/postinstall.js](https://github.com/twilio/twilio-conversations.js/blob/master/scripts/postinstall.js#L4) to use `path.join` to construct the symlink paths instead of constructing them manually with "/".

**Comment by ZuSe** [comment]
@markandrus 

Thanks for the fast answer. It works for me under OSX and Windows (after installing python2.7 and running npm install in an administrator cmd).

All Ubuntu systems are broken. I am running nodejs 5.3.0 locally. Our build servers (jenkins + Cloud Foundry) depend on nodejs 4.2.4 LTS .. same problem. 

Makes it really hard to use twilio-conversations in production.

**Comment by markandrus** [comment]
@ZuSe ah, i now see that this is an NPM v3 issue. i will see about a fix.
