### ISSUE TITLE
Error on IncomingInvite.reject()

### ISSUE THREAD

**Issue by talihomz** [twilio/twilio-conversations.js#7]
Im using twilio sdk to connect to another client, and when i want to reject an incoming call, i get the following error message:

`Error: Cannot read property 'once' of undefined
TypeError: Cannot read property 'once' of undefined
    at r._dialogCreated (twilio-conversations.min.js:90)
    at r._onInviteSuccess (twilio-conversations.min.js:90)
    at dynamics_browser.js:51`.

Have checked the docs on the proper way to do a reject call and cannot see what i'm doing wrong so far

**Comment by markandrus** [comment]
Thanks for the report @talihomz, will take a look.

**Comment by choppen5** [comment]
This can be closed -  I gave a code sample of rejecting an inivite that did work:  https://github.com/choppen5/twilioVideo/blob/master/public/quickstart.js#L39
